---
- name: (HANDLER) Restart ddns service
  ansible.builtin.systemd_service:
    daemon_reload: true
    enabled: true
    masked: false
    state: restarted
    name: "{{ item }}"
  loop: [ddns.service, ddns.timer]
  listen: handler_restart_ddns
